version: '3.8'
services:
  converter-backend:
    build:
      context: .
      dockerfile: converter-backend/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
  converter-frontend:
    build:
      context: ./converter-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
